//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalProductores.Infrastructure.Constants {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FieldNameConstants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FieldNameConstants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PortalProductores.Infrastructure.Constants.FieldNameConstants", typeof(FieldNameConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad de Envases.
        /// </summary>
        public static string CantidadEnvases {
            get {
                return ResourceManager.GetString("CantidadEnvases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro.
        /// </summary>
        public static string CentroNombre {
            get {
                return ResourceManager.GetString("CentroNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Proceso.
        /// </summary>
        public static string FechaProceso {
            get {
                return ResourceManager.GetString("FechaProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Recepción.
        /// </summary>
        public static string FechaRecepcion {
            get {
                return ResourceManager.GetString("FechaRecepcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guía Despacho.
        /// </summary>
        public static string Guia {
            get {
                return ResourceManager.GetString("Guia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesados (Kg).
        /// </summary>
        public static string KilosProcesados {
            get {
                return ResourceManager.GetString("KilosProcesados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recepción (Kg).
        /// </summary>
        public static string KilosRecepcionados {
            get {
                return ResourceManager.GetString("KilosRecepcionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lote Proceso.
        /// </summary>
        public static string Lote {
            get {
                return ResourceManager.GetString("Lote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Partida.
        /// </summary>
        public static string NumeroPartida {
            get {
                return ResourceManager.GetString("NumeroPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % de Exportación.
        /// </summary>
        public static string PorcentajeExportacion {
            get {
                return ResourceManager.GetString("PorcentajeExportacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productor.
        /// </summary>
        public static string ProductorNombre {
            get {
                return ResourceManager.GetString("ProductorNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variedad.
        /// </summary>
        public static string VariedadNombre {
            get {
                return ResourceManager.GetString("VariedadNombre", resourceCulture);
            }
        }
    }
}
