//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalProductores.Infrastructure.Constants {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QueryConstants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QueryConstants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PortalProductores.Infrastructure.Constants.QueryConstants", typeof(QueryConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from UsuarioProductor where UsuarioId = @UsuarioId
        ///delete from Usuario where Id = @UsuarioId.
        /// </summary>
        public static string DeleteUsuarioById {
            get {
                return ResourceManager.GetString("DeleteUsuarioById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from UsuarioProductor where UsuarioId = @UsuarioId.
        /// </summary>
        public static string DeleteUsuarioProductorByUsuarioId {
            get {
                return ResourceManager.GetString("DeleteUsuarioProductorByUsuarioId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select COUNT(1) 
        ///from Proceso WITH(NOLOCK).
        /// </summary>
        public static string GetCountProcesos {
            get {
                return ResourceManager.GetString("GetCountProcesos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select COUNT(1) 
        ///from Productor WITH(NOLOCK)
        ///where Estado = 1.
        /// </summary>
        public static string GetCountProductores {
            get {
                return ResourceManager.GetString("GetCountProductores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select COUNT(1) 
        ///from Recepcion WITH(NOLOCK).
        /// </summary>
        public static string GetCountRecepciones {
            get {
                return ResourceManager.GetString("GetCountRecepciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select COUNT(1) 
        ///from Usuario WITH(NOLOCK).
        /// </summary>
        public static string GetCountUsuarios {
            get {
                return ResourceManager.GetString("GetCountUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *
        ///from (
        ///	select
        ///		p.ProductorPadreId,
        ///		pp.Nombre ProductorPadreNombre,
        ///		p.Id ProductorId,
        ///		p.Nombre ProductorNombre,
        ///		v.Id VariedadId,
        ///		v.Nombre VariedadNombre,
        ///		pr.Lote,
        ///		pr.FechaProceso,
        ///		c.Id CentroId,
        ///		c.Nombre CentroNombre,
        ///		pr.KilosProcesados,
        ///		pr.PorcentajeExportacion,
        ///		pr.TemporadaId,
        ///		pr.EspecieId
        ///	from Proceso pr WITH(NOLOCK)
        ///	inner join Productor p WITH(NOLOCK) on p.Id = pr.ProductorId
        ///	inner join Variedad v WITH(NOLOCK) on v.Id = pr.VariedadId
        ///	inner join [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetListProcesos {
            get {
                return ResourceManager.GetString("GetListProcesos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *
        ///from (
        ///	select 
        ///		p.Id,
        ///		p.CodigoSAP,
        ///		p.Nombre,
        ///		p.Rut,
        ///		p.Correo,
        ///		p.ProductorPadreId,
        ///		pp.CodigoSAP CodigoSAPPadre,
        ///		pp.Nombre NombrePadre,
        ///		pp.Rut RutPadre,
        ///		pp.Correo CorreoPadre
        ///	from Productor p WITH(NOLOCK)
        ///	left join Productor pp WITH(NOLOCK) on pp.Id = p.ProductorPadreId
        ///	where p.Estado = 1
        ///) data
        ///where 1 = 1.
        /// </summary>
        public static string GetListProductores {
            get {
                return ResourceManager.GetString("GetListProductores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *
        ///from (
        ///	select
        ///		pp.Id ProductorPadreId,
        ///		pp.Nombre ProductorPadreNombre,
        ///		p.Id ProductorId,
        ///		p.Nombre ProductorNombre,
        ///		r.TemporadaId,
        ///		r.EspecieId,
        ///		r.VariedadId,
        ///		v.Nombre VariedadNombre,
        ///		r.Guia,
        ///		r.NumeroPartida,
        ///		r.FechaRecepcion,
        ///		r.CantidadEnvases,
        ///		r.KilosRecepcionados,
        ///		r.Estado,
        ///		case
        ///			when r.Estado = 0 then &apos;Inactivo&apos;
        ///			when r.Estado = 1 then &apos;Activo&apos;
        ///			when r.Estado = 2 then &apos;Aprobado&apos;
        ///			when r.Estado = 3 then &apos;Rechazado&apos;
        ///			when r.Estado = 4 th [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetListRecepciones {
            get {
                return ResourceManager.GetString("GetListRecepciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select up.UsuarioId, up.ProductorId, p.Rut RutProductor, p.Nombre NombreProductor
        ///from UsuarioProductor up WITH(NOLOCK)
        ///inner join Productor p WITH(NOLOCK) on p.Id = up.ProductorId
        ///where up.UsuarioId = @UsuarioId.
        /// </summary>
        public static string GetListUsuarioProductorByUsuarioId {
            get {
                return ResourceManager.GetString("GetListUsuarioProductorByUsuarioId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *
        ///from (
        ///	select 
        ///	u.Id, 
        ///	u.Nombre, 
        ///	u.Correo,
        ///	case 
        ///		when u.Perfil = 1 then &apos;Administrador&apos;
        ///		when u.Perfil = 2 then &apos;Estándar&apos;
        ///		when u.Perfil = 3 then &apos;Productor&apos;
        ///	end TipoPerfil
        ///	from Usuario u WITH(NOLOCK)
        ///) data
        ///where 1 = 1.
        /// </summary>
        public static string GetListUsuarios {
            get {
                return ResourceManager.GetString("GetListUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select p.Id ProductorId
        ///from Productor p WITH(NOLOCK)
        ///where Id in ({0}).
        /// </summary>
        public static string ValidateExistsProductores {
            get {
                return ResourceManager.GetString("ValidateExistsProductores", resourceCulture);
            }
        }
    }
}
